YourLocalization.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using YourLocalization.Web.Models;

namespace YourLocalization.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult SelectRegister()
        {
            return View();
        }

        public IActionResult Logout()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

YourLocalization.Web/Controllers/PointController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using YourLocalization.Application.Interfaces;
using YourLocalization.Application.ViewModels.Point;

namespace YourLocalization.Web.Controllers
{
    public class PointController : Controller
    {
        private readonly IPointService _pointService;
        private readonly ITypeService _typeService;
        private readonly ISubtypeService _subtypeService;

        public PointController(IPointService pointService, ITypeService typeService, ISubtypeService subtypeService)
        {
            _pointService = pointService;
            _typeService = typeService;
            _subtypeService = subtypeService;
        }

        [Authorize(Roles = "Admin")]
        [HttpGet("points")]
        public IActionResult Index()
        {
            var model = _pointService.GetAllPointsForList(10, 1, "");
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost("points")]
        public IActionResult Index(int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }

            var model = _pointService.GetAllPointsForList(pageSize, pageNo.Value, searchString);
            return View(model);
        }

        [Authorize(Roles = "User, Admin")]
        [HttpGet("userpoints")]
        public IActionResult ViewUserPoints()
        {
            string name = HttpContext.User.Identity.Name; 
            var model = _pointService.GetUserPointsForList(name, 10, 1, "");
            return View(model);
        }

        [Authorize(Roles = "User, Admin")]
        [HttpPost("userpoints")]
        public IActionResult ViewUserPoints(string name, int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }

            var model = _pointService.GetUserPointsForList(name, pageSize, pageNo.Value, searchString);
            return View(model);
        }

        [Authorize(Roles = "User, Admin")]
        [HttpGet]
        public IActionResult AddPoint()
        {
            var newPointVm = new NewPointVm();
            newPointVm.Types = _typeService.GetAllTypesToDropDownList();
            newPointVm.Subtypes = _subtypeService.GetAllSubtypesToDropDownList();
            return View(newPointVm);
        }

        [Authorize(Roles = "User, Admin")]
        [HttpPost]
        public IActionResult AddPoint(NewPointVm model)
        {
            int id = _pointService.AddPoint(model);
            return RedirectToAction("ViewUserPoints");
        }

        [Authorize(Roles = "User, Admin")]
        [HttpGet("point/details/{pointId}")]
        public IActionResult ViewPoint(int pointId)
        {
            var pointModel = _pointService.GetPointDetails(pointId);
            return View(pointModel);
        }

        [Authorize(Roles = "User, Admin")]
        [HttpGet]
        public IActionResult EditPoint(int id)
        {
            NewPointVm point = _pointService.GetPointForEdit(id);
            point.Types = _typeService.GetAllTypesToDropDownList();
            return View(point);
        }

        [Authorize(Roles = "User, Admin")]
        [HttpPost]
        public IActionResult EditPoint(NewPointVm model)
        {
            _pointService.UpdatePoint(model);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "User, Admin")]
        public IActionResult DeletePoint(int id)
        {
            _pointService.DeletePoint(id);
            return RedirectToAction("Index");
        }
    }
}

YourLocalization.Web/Controllers/TypeController.cs
using Microsoft.AspNetCore.Mvc;
using YourLocalization.Application.Interfaces;
using YourLocalization.Application.ViewModels.Type;

namespace YourLocalization.Web.Controllers
{
    public class TypeController : Controller
    {
        private readonly ITypeService _typeService;

        public TypeController(ITypeService typeService)
        {
            _typeService = typeService;
        }

        [HttpGet("types")]
        public IActionResult Index()
        {
            var model = _typeService.GetAllTypeForList(9, 1, "");
            return View(model);
        }

        [HttpPost("types")]
        public IActionResult Index(int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }

            var model = _typeService.GetAllTypeForList(pageSize, pageNo.Value, searchString);
            return View(model);
        }

        [HttpGet]
        public IActionResult AddType()
        {
            return View(new NewTypeVm());
        }

        [HttpPost]
        public IActionResult AddType(NewTypeVm model)
        {
            var id = _typeService.AddType(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditType(int id)
        {
            var type = _typeService.GetTypeForEdit(id);
            return View(type);
        }

        [HttpPost]
        public IActionResult EditType(NewTypeVm model)
        {
            _typeService.UpdateType(model);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteType(int id)
        {
            _typeService.DeleteType(id);
            return RedirectToAction("Index");
        }
    }
}

YourLocalization.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using YourLocalization.Application.Interfaces;
using YourLocalization.Application.ViewModels.User;

namespace YourLocalization.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet("users")]
        public IActionResult Index()
        {
            var model = _userService.GetAllUsersForList(2, 1, "");
            return View(model);
        }

        [HttpPost("users")]
        public IActionResult Index(int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }

            var model = _userService.GetAllUsersForList(pageSize, pageNo.Value, searchString);
            return View(model);
        }

        [HttpGet]
        public IActionResult AddUser() //metoda ta zwraca pusty formularz który użytkownik będzie musiał wypełnić
        {
            return View(new NewUserVm());
        }

        [HttpPost]
        public IActionResult AddUser(NewUserVm model)
        {
            string id = _userService.AddUser(model);
            return RedirectToAction("Index");
        }

        //[HttpGet]
        //public IActionResult AddNewAddressForClient(int userId)
        //{
        //    return View();
        //}

        //[HttpPost]
        //public IActionResult AddNewAddressForClient(AddressModel model)
        //{
        //    return View();
        //}

        [HttpGet("user/details/{userId}")]
        public IActionResult ViewUser(string userId)
        {
            var userModel = _userService.GetUserDetails(userId);
            return View(userModel);
        }
    }
}

YourLocalization.Web/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using YourLocalization.Domain.Model
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@{
    ViewData["Title"] = "Menu";
}

<div class="text-center">
    @if (SignInManager.IsSignedIn(User))
    {
        <h3 class="display-4">YOUR'S MENU</h3>
        <br>
        <br>

        @if (User.IsInRole("Admin"))
        {
            <a class="btn btn-primary" asp-area="" asp-controller="User" asp-action="Index">List of users</a>
            <a class="btn btn-primary" asp-area="" asp-controller="User" asp-action="AddUser">Add new user</a>
        }
        <br>
        <br>
        @if (User.IsInRole("Admin"))
        {
            <a class="btn btn-primary" asp-area="" asp-controller="Point" asp-action="Index">List of points</a>
            <a class="btn btn-primary" asp-area="" asp-controller="Point" asp-action="AddPoint">Add new point</a>
        }
        <br>
        <br>
        @if (User.IsInRole("Admin"))
        {
            <a class="btn btn-primary" asp-area="" asp-controller="Type" asp-action="Index">List of point types</a>
            <a class="btn btn-primary" asp-area="" asp-controller="Type" asp-action="AddType">Add new point type</a>
        }
    }

</div>

YourLocalization.Web/Views/Home/Logout.cshtml
@{
    ViewData["Title"] = "Logout";
}


<div class="text-center">
    <br>
    <br>
    <h4>You have been logged out successfully!</h4>
    <br>
    <h6>It was nice to see you.</h6>
    <br>
</div>

YourLocalization.Web/Views/Home/SelectRegister.cshtml
@using Microsoft.AspNetCore.Identity
@using YourLocalization.Domain.Model
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@{
    ViewData["Title"] = "Select Register";
}


@if ((!SignInManager.IsSignedIn(User)) || (User.IsInRole("Admin")))
{
    <div class="text-center">
        <style>
            .card:hover {
                box-shadow: -1px 9px 40px -12px #808080;
            }
        </style>
        <h2> Who are you?</h2>
        <div class="col d-flex justify-content-center">
            <div class="row">
                <div class="card" style="width:20em;margin:10px;">
                    <img src="~/1.png" class="card-img-top" />
                    <div class="card-body">
                        <div class="card-title">
                            <h2>I'm user</h2>
                        </div>
                        <div class="card-text">
                            <p>Do you want to report the location of a shop, hairdresser or other place that you think is missing in your area?</p>
                        </div>
                        <a class="btn btn-outline-primary" asp-area="Identity" asp-page="/Account/Register" asp-route-isCustomer="false">Register</a>
                    </div>
                </div>
                <div class="card" style="width:20em;margin:10px;">
                    <img src="~/2.png" class="card-img-top" />
                    <div class="card-body">
                        <div class="card-title">
                            <h2>I'm customer</h2>
                        </div>
                        <div class="card-text">
                            <p>
                                <br>
                                Or would you like to see where the community needs your business?
                                <br>
                                <br>
                            </p>
                        </div>
                        <a class="btn btn-outline-warning" asp-area="Identity" asp-page="/Account/Register" asp-route-isCustomer="true">Register</a>
                    </div>
                </div>
            </div>
        </div>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script type="text/javascript">
            $('.card').hover(
                function () {
                    $(this).animate({
                        marginTop: "-=1%",
                        marginBottom: "+=1%"
                    }, 200)
                },
                function () {
                    $(this) animate({
                        marginTop: "+=1%",
                        marginBottom: "-=1%"
                    },)
                }
            )
        </script>
    </div>

}
@if ((User.IsInRole("User")) || (User.IsInRole("Admin")))
{
    <div class="text-center">
        <style>
            .card:hover {
            box-shadow: -1px 9px 40px -12px #808080;
            }
        </style>
        <div class="col d-flex justify-content-center">
            <div class="row">
                <div class="card" style="width:30em;margin:10px;">
                    <div class="card-title" style="margin-top:30px">
                        <h2>Welcome to YourLocalization @User.Identity.Name ! </h2>
                    </div>
                    <img src="https://img.freepik.com/darmowe-wektory/lokalizacja_53876-25530.jpg" class="rounded mx-auto d-block" style="max-width:70%;" />
                    <div class="card-body">
                        <div class="card-text">
                            <p>You can add new point to report the location of a shop, hairdresser or other place that you think is missing in your area.</p>
                        </div>
                        <a class="btn btn-outline-primary" asp-controller="Point" asp-action="AddPoint">Go to report location</a>
                    </div>
                </div>
            </div>
        </div>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script type="text/javascript">
            $('.card').hover(
            function () {
            $(this).animate({
            marginTop: "-=1%",
            marginBottom: "+=1%"
            }, 200)
            },
            function () {
            $(this) animate({
            marginTop: "+=1%",
            marginBottom: "-=1%"
            },)
            }
            )
        </script>
    </div>
}


@if ((User.IsInRole("Customer")) || (User.IsInRole("Admin")))
{
    <div class="text-center">
        <style>
            .card:hover {
            box-shadow: -1px 9px 40px -12px #808080;
            }
        </style>
        <div class="col d-flex justify-content-center">
            <div class="row">
                <div class="card" style="width:30em;margin:10px;">
                    <div class="card-title" style="margin-top:30px">
                        <h2>Welcome to YourLocalization @User.Identity.Name ! </h2>
                    </div>
                    <img src="https://img.freepik.com/free-vector/check-cross-flat-boxes_78370-638.jpg?w=360" class="rounded mx-auto d-block" style="max-width:70%;" />
                    <div class="card-body">
                        <div class="card-text">
                            <p>You can check where the community needs your business.</p>
                        </div>
                        <a class="btn btn-outline-primary" asp-controller="Point" asp-action="">Go to chceck location</a>
                    </div>
                </div>
            </div>
        </div>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script type="text/javascript">
            $('.card').hover(
            function () {
            $(this).animate({
            marginTop: "-=1%",
            marginBottom: "+=1%"
            }, 200)
            },
            function () {
            $(this) animate({
            marginTop: "+=1%",
            marginBottom: "-=1%"
            },)
            }
            )
        </script>
    </div>
}