YourLocalization.Web/Controllers/PointController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using YourLocalization.Application.Interfaces;
using YourLocalization.Application.ViewModels.Point;

namespace YourLocalization.Web.Controllers
{
    public class PointController : Controller
    {
        private readonly IPointService _pointService;
        private readonly ITypeService _typeService;
        private readonly ISubtypeService _subtypeService;

        public PointController(IPointService pointService, ITypeService typeService, ISubtypeService subtypeService)
        {
            _pointService = pointService;
            _typeService = typeService;
            _subtypeService = subtypeService;
        }

        [Authorize(Roles = "Admin")]
        [HttpGet("points")]
        public IActionResult Index()
        {
            var model = _pointService.GetAllPointsForList(10, 1, "");
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost("points")]
        public IActionResult Index(int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }

            var model = _pointService.GetAllPointsForList(pageSize, pageNo.Value, searchString);
            return View(model);
        }

        [Authorize(Roles = "User, Admin")]
        [HttpGet("userpoints")]
        public IActionResult ViewUserPoints()
        {
            string name = HttpContext.User.Identity.Name; 
            var model = _pointService.GetUserPointsForList(name, 10, 1, "");
            return View(model);
        }

        [Authorize(Roles = "User, Admin")]
        [HttpPost("userpoints")]
        public IActionResult ViewUserPoints(string name, int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }

            var model = _pointService.GetUserPointsForList(name, pageSize, pageNo.Value, searchString);
            return View(model);
        }

        [Authorize(Roles = "User, Admin")]
        [HttpGet]
        public IActionResult AddPoint()
        {
            var newPointVm = new NewPointVm();
            newPointVm.Types = _typeService.GetAllTypesToDropDownList();
            newPointVm.Subtypes = _subtypeService.GetAllSubtypesToDropDownList();
            return View(newPointVm);
        }

        [Authorize(Roles = "User, Admin")]
        [HttpPost]
        public IActionResult AddPoint(NewPointVm model)
        {
            int id = _pointService.AddPoint(model);
            return RedirectToAction("ViewUserPoints");
        }

        [Authorize(Roles = "User, Admin")]
        [HttpGet("point/details/{pointId}")]
        public IActionResult ViewPoint(int pointId)
        {
            var pointModel = _pointService.GetPointDetails(pointId);
            return View(pointModel);
        }

        [Authorize(Roles = "User, Admin")]
        [HttpGet]
        public IActionResult EditPoint(int id)
        {
            NewPointVm point = _pointService.GetPointForEdit(id);
            point.Types = _typeService.GetAllTypesToDropDownList();
            return View(point);
        }

        [Authorize(Roles = "User, Admin")]
        [HttpPost]
        public IActionResult EditPoint(NewPointVm model)
        {
            _pointService.UpdatePoint(model);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "User, Admin")]
        public IActionResult DeletePoint(int id)
        {
            _pointService.DeletePoint(id);
            return RedirectToAction("Index");
        }
    }
}

YourLocalization.Web/Controllers/SubtypeController.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using YourLocalization.Application.Interfaces;
using YourLocalization.Application.Services;
using YourLocalization.Application.ViewModels.Point;
using YourLocalization.Application.ViewModels.Subtype;
using YourLocalization.Application.ViewModels.Type;
using YourLocalization.Domain.Model;

namespace YourLocalization.Web.Controllers
{
    public class SubtypeController : Controller
    {
        private readonly ISubtypeService _subtypeService;
        private readonly ITypeService _typeService;

        public SubtypeController(ISubtypeService subtypeService, ITypeService typeService)
        {
            _subtypeService = subtypeService;
            _typeService = typeService;
        }

        [HttpGet("subtypes")]
        public IActionResult Index()
        {
            var model = _subtypeService.GetAllSubtypeForList(9, 1, "");
            return View(model);
        }

        [HttpPost("subtypes")]
        public IActionResult Index(int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }

            var model = _subtypeService.GetAllSubtypeForList(pageSize, pageNo.Value, searchString);
            return View(model);
        }

        [HttpGet]
        public IActionResult AddSubtype()
        {
            var newSubtypeVm = new NewSubtypeVm();
            newSubtypeVm.Types = _typeService.GetAllTypesToDropDownList();
            return View(newSubtypeVm);
        }

        [HttpPost]
        public IActionResult AddSubtype(NewSubtypeVm model)
        {
            var id = _subtypeService.AddSubtype(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditSubtype(int id)
        {
            NewSubtypeVm editSubtypeVm = _subtypeService.GetSubtypeForEdit(id);
            editSubtypeVm.Types = _typeService.GetAllTypesToDropDownList();
            return View(editSubtypeVm);
        }

        [HttpPost]
        public IActionResult EditSubtype(NewSubtypeVm model)
        {
            _subtypeService.UpdateSubtype(model);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteSubtype(int id)
        {
            _subtypeService.DeleteSubtype(id);
            return RedirectToAction("Index");
        }
    }
}

YourLocalization.Web/Controllers/TypeController.cs
using Microsoft.AspNetCore.Mvc;
using YourLocalization.Application.Interfaces;
using YourLocalization.Application.ViewModels.Type;

namespace YourLocalization.Web.Controllers
{
    public class TypeController : Controller
    {
        private readonly ITypeService _typeService;

        public TypeController(ITypeService typeService)
        {
            _typeService = typeService;
        }

        [HttpGet("types")]
        public IActionResult Index()
        {
            var model = _typeService.GetAllTypeForList(9, 1, "");
            return View(model);
        }

        [HttpPost("types")]
        public IActionResult Index(int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }

            var model = _typeService.GetAllTypeForList(pageSize, pageNo.Value, searchString);
            return View(model);
        }

        [HttpGet]
        public IActionResult AddType()
        {
            return View(new NewTypeVm());
        }

        [HttpPost]
        public IActionResult AddType(NewTypeVm model)
        {
            var id = _typeService.AddType(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditType(int id)
        {
            var type = _typeService.GetTypeForEdit(id);
            return View(type);
        }

        [HttpPost]
        public IActionResult EditType(NewTypeVm model)
        {
            _typeService.UpdateType(model);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteType(int id)
        {
            _typeService.DeleteType(id);
            return RedirectToAction("Index");
        }
    }
}

YourLocalization.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using YourLocalization.Domain.Model
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YourLocalization</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/YourLocalization.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="SelectRegister">YourLocalization</a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin") || User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="SelectRegister">Home</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Points
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-controller="Point" asp-action="AddPoint">Add new point</a></li>
                                    <li><a class="dropdown-item" asp-controller="Point" asp-action="ViewUserPoints">My points</a></li>
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <li><a class="dropdown-item" asp-controller="Point" asp-action="Index">All points</a></li>
                                    }
                                </ul>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Types
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="Type" asp-action="AddType">Add new type</a></li>
                                <li><a class="dropdown-item" asp-controller="Type" asp-action="Index">All types</a></li>
                                
                            </ul>
                        </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Subtypes
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-controller="Subtype" asp-action="AddSubtype">Add new subtype</a></li>
                                    <li><a class="dropdown-item" asp-controller="Subtype" asp-action="Index">All subtypes</a></li>

                                </ul>
                            </li>
                        }
                    </ul>
                    
                    <partial name="_LoginPartial" />
                </div>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - YourLocalization.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>